### ISSUE TITLE
Inconsistent CR LF characters lead to hard co-editing on GitHub

### ISSUE THREAD

**Issue by doggy8088** [dotnet/docs.zh-tw#157]
Hi,

I was realized that all the docs in this repo contains many of the Inconsistant CR LF characters.  Everytime I edit on GitHub will cause git diff become very hard to read due to CRLF issue.

Please check the following screenshot.  The header part use the CRLF as a newline characters.  The body part use the LF as a newline character.

![image](https://user-images.githubusercontent.com/88981/35180002-e1497c68-fde0-11e7-9323-b4ad06bc88db.png)

Hope this can be fixed.

**Comment by doggy8088** [comment]
@v-radelg Do you aware this issue?

**Comment by Sara-Nicolini** [comment]
@nokura, can you please investigate?

**Comment by doggy8088** [comment]
Does anyone watching this?

**Comment by mairaw** [comment]
Let me follow up with the team offline

**Comment by nokura** [comment]
Microsoft updated our internal localization tool to generate the consistent line ending (LF). However, this fix will be applied only going forward (only topics updated, translated and published from now on).
As we keep localizing the updated files, the issue will be resolved over time.

**Comment by Maledong** [comment]
@nokura：Just for a confirm：So you mean `CRLF` will be repalaced by `LF` automatically and we don't need to anything for that, even there're a lots of differences when comparing with each other?
