### ISSUE TITLE
DO & DO NOT 翻譯問題

### ISSUE THREAD

**Issue by jason8399** [dotnet/docs.zh-tw#166]
DO 於 “[命名方針](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/design-guidelines/capitalization-conventions.md)” 中 翻譯為 “不要”
應該修正為“請” or “請使用”

**Comment by CeciAc** [comment]
@jason8399 您好，我們仍然在討論您的建議，會儘速於稍後做出結論。 
 
感謝您的支持， 
Microsoft C&E 當地語系化小組敬上

**Comment by CeciAc** [comment]
@jason8399  您好，感謝您的意見反應及建議！  
	 
我們會將您的建議納入考量，此文章會在下次當地語系化時發佈。 
	 
Microsoft C&E 當地語系化小組敬上
