### ISSUE TITLE
Next page text is wrong

### ISSUE THREAD

**Issue by cocoaswifty** [dotnet/docs.zh-tw#176]
https://i.imgur.com/xOQ6dDV.png

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: 8843df22-85a5-c35b-864b-0b18864e5347
* Content: [使用 ASP.NET Core 應用程式中的資料](https://docs.microsoft.com/zh-tw/dotnet/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @cocoaswifty,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @cocoaswifty
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/dotnet/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
