### ISSUE TITLE
逸出字元"\S"問題詢問

### ISSUE THREAD

**Issue by yuyueh** [dotnet/docs.zh-tw#178]
您好。本頁介紹中提到的逸出字元"\S"，最後"int _ctr"符合的結果應為" _"而非" "。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [規則運算式語言 - 快速參考](https://docs.microsoft.com/zh-tw/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gosali** [comment]
Issue moved to [dotnet/docs #6320](https://github.com/dotnet/docs/issues/6320) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gosali** [comment]
您好，@yuyueh，
 
非常感謝您的貢獻。您的意見反應與原始文件相關。
 
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態   - https://github.com/dotnet/docs/issues/6320。
  
我們由衷感謝您對文章的貢獻。

 
順頌時祺 
Microsoft DOCS 國際小組
