### ISSUE TITLE
錨點$問題

### ISSUE THREAD

**Issue by yuyueh** [dotnet/docs.zh-tw#179]
錨點"$"說明中， "-333-333-" 中的結果不應該為"-333"。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [規則運算式語言 - 快速參考](https://docs.microsoft.com/zh-tw/dotnet/standard/base-types/regular-expression-language-quick-reference#atomic_zerowidth_assertions)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gosali** [comment]
Issue moved to [dotnet/docs #6319](https://github.com/dotnet/docs/issues/6319) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gosali** [comment]
您好，@yuyueh,
 
非常感謝您的貢獻。您的意見反應與原始文件相關。
 
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態   - https://github.com/dotnet/docs/issues/6319。
  
我們由衷感謝您對文章的貢獻。
   
順頌時祺 
Microsoft DOCS 國際小組

**Comment by rpetrusha** [comment]
I'm not sure why this issue has been closed and moved to dotnet/docs; this is a localization issue, not a source repo issue. The issue does not exist in the [en-US](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#anchors) version.

**Comment by mairaw** [comment]
@gosali @nokura I've reopened the issue here since this is not a source issue, but a loc issue,

**Comment by CeciAc** [comment]
您好，@yuyueh @ooxxTaiwan
謝謝您的寶貴意見。 
我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 XXX。  
我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。 
順頌時祺 
Microsoft DOCS 國際小組
