### ISSUE TITLE
Use "以傳址方式" to express "pass* by reference" may be ambiguous because it can also means "pass* by address".

### ISSUE THREAD

**Issue by abc1236762** [dotnet/docs.zh-tw#188]
I suggest using "以傳參考方式" instead of "以傳址方式" to express "pass* by reference" in Traditional Chinese.
First, "reference" in Traditional Chinese (Taiwan usage) is "參考". Refer to Simplified Chinese version, it uses "按引用传递" to express "passed by reference", and "引用" exactly is "reference" in Simplified Chinese (China usage).
Second, "址" in English is "address", so "以傳址方式" can be translated into "pass by address" in English. Passing by address is the same as passing the pointer, but passing by reference is different with passing by address/pointer.
Also, use 傳參考 to express passing by reference is more popular than 傳址 in Traditional Chinese. 傳址 means passing by address/pointer more often.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref (C# 參考)](https://docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/keywords/ref#feedback)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/csharp/language-reference/keywords/ref.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @abc1236762 ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @abc1236762 ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by abc1236762** [comment]
Why reopened? Are there any other questions that I didn't have the clear explanation?

**Comment by CeciAc** [comment]
Hi @abc1236762 ,
 Don't worry, no action is required from your side. The linguistic suggestion was accepted and will be implemented in the next round, we'll just leave this open until the implementation is effective.

Sorry about the confusion.

Microsoft DOCS International Team
