### ISSUE TITLE
Inconsistent translations

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs.zh-tw#212]
https://github.com/dotnet/docs.zh-tw/blob/e2355923d6c242a23845bea6b2228f6db5016649/docs/standard/base-types/regular-expression-language-quick-reference.md#L158-L159

The translations of "alternation constructs" should be consistent.

**Comment by v-maudel** [comment]
Hello, @NextTurn 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @NextTurn 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages docs.zh-tw/docs/standard/base-types/regular-expression-language-quick-reference.md 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
