### ISSUE TITLE
本國語文能力好，理解教授沒煩惱

### ISSUE THREAD

**Issue by oscarsun72** [dotnet/docs.zh-tw#225]
唉 該怎麼說了 static 靜態方法也好、靜態類別（class）也罷，什麼東東靜態 才是關鍵啊。
不是方法和類別本身在靜態，是它們被配置的記憶體空間變化和配置次數是靜態的。一經配置，就不動了，所以叫「靜態」！一直到整個方案結束、應用程式終止，都不會再變動了，所以叫「靜態」！
國文不好，難怪什麼都好不起來。為什麼會一頭霧水，捉不著邊，因為大家都愛用文言取名，不愛用白話說明嘛！
靜態，的主詞是記憶體，是建構子，是說建構子（建構函式、建構式、建構函數、構造函數 constructor）一次建構後，便靜態了。建構就是配置記憶體位置與空間嘛！所以才叫它是「靜態」的。不搞清楚「靜態」的「主詞」是誰（九陽神功第8招「找對主詞」）又怎麼讀得懂、搞得清楚明白EZ呢？ 都是國文不好惹的禍嘛！

取名字，不可能像白話文那樣「躼躼長」，所以恆愛用文言文（即多是縮語、省稱--即文言愛用的單字構詞模式，或如此這般的省略式--省略主詞），那麼文言文不好行嗎？為什麼必須國文，懂嗎？不是我們國文專業的老王賣瓜，好嗎？
予豈好辯哉！科學事實擺在眼前，您能不信嗎？
【這個問題曾經困擾了筆者很久……後來筆者才搞懂String.IsNullOrEmpty()是靜態方法static function。同樣的案例發身在C/C++、JAVA身上都有。筆者身邊有一些朋友一直搞不懂這是甚麼意思】
https://ithelp.ithome.com.tw/articles/10184803

不是各位大大程式語言能力不強，是國文能力有差啦！誰，不需要用語文來溝通、來學習，來理解呢？我們用中文漢字為母語的，自然就得學好這個語文；否則就一律用原文就好嘛；可問題又來了，您原文的能力，會有母語更好嗎？那就祝福您了。

以後再不知天高地厚就在那大叫對什麼感興趣，對什麼不感興趣，往往都是在不感興趣的地方栽跟頭，因為無明無知的，還是幼稚而自以為是的封閉心靈呀。

天啊「躼」連我這個中文博士畢生也僅見，還敢小看閩南語臺灣話嗎？ 中文啊，國文也，學不完的啦！南無阿彌陀佛
http://blog.udn.com/rosylovesyou/5521379

提昇自己語文能力的十七招基本功示例，二套心法開源傳授：
九陽神功：http://bit.ly/2AJgyFX
七星大法：http://bit.ly/2yQITZF

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 7f20db0d-ef5c-d8e7-2267-0f409c499e0f
* Version Independent ID: de2dac73-e810-dd42-f518-e50926b3747f
* Content: [靜態類別和靜態類別成員 - C# 程式設計手冊](https://docs.microsoft.com/zh-tw/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
您好 @oscarsun72 
 謝謝您的寶貴意見。 
 我們目前正在檢閱您的留言，將會盡快與您連絡。 
 順頌時祺 
Microsoft DOCS 國際小組

**Comment by CeciAc** [comment]
您好，@oscarsun72
非常感謝您所回饋的意見。
您所分享的觀點勢必能協助我們持續改善使用者與讀者的體驗。
順頌時祺
Microsoft DOCS 國際小組

**Comment by oscarsun72** [comment]
Thank you for your appreciation.
