### ISSUE TITLE
文章內容名詞錯誤

### ISSUE THREAD

**Issue by darkleong** [dotnet/docs.zh-tw#238]
段落：throw 運算式
內容：運算式主體 ambda 或方法。 
不是"ambda"，應該是"lambda"才對。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d79f0472-2434-9724-979f-2d5eb281dd67
* Version Independent ID: 6c665c3e-93ac-cc9e-4d68-91e8cf285ed5
* Content: [throw - C# 參考](https://docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/keywords/throw#feedback)
* Content Source: [docs/csharp/language-reference/keywords/throw.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/csharp/language-reference/keywords/throw.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @darkleong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
您好，@darkleong
謝謝您的寶貴意見。 
我們的編審小組審閱了您提出的語言建議，並接受了這些建議。
我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。 
順頌時祺 
Microsoft DOCS 國際小組
