### ISSUE TITLE
Hello.dll to Hello.exe

### ISSUE THREAD

**Issue by Ziv81** [dotnet/docs.zh-tw#243]
https://github.com/dotnet/docs.zh-tw/blob/live/docs/core/tutorials/using-with-xplat-cli.md

$ dotnet bin\Debug\netcoreapp2.1\publish\Hello.dll
should be 
$ dotnet bin\Debug\netcoreapp2.1\publish\Hello.exe

**Comment by srvbpigh** [comment]
Hello, @Ziv81
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
Not true. You can use either `dotnet .../hello.dll` or `.../hello.exe`, but not `dotnet .../hello.exe`.

**Comment by Ziv81** [comment]
Sorry, I forget to add dotnet in the begin and make it hava error.
