### ISSUE TITLE
miss written character

### ISSUE THREAD

**Issue by s0920832252** [dotnet/docs.zh-tw#263]
傳回IEnumerator object或IEnumerable的反覆運算器產生類型為 object。
傳回IEnumerator<T> T或IEnumerable<T>的反覆運算器產生類型為 T。

為object 以及為 T 在文件上消失了.
---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d94b01ab-fe87-23fc-44b6-da9f3f627bd5
* Version Independent ID: a86008b1-2fdd-bbb9-3bbf-8fc8c51c1b71
* Content: [Classes - C# language specification](https://docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/language-specification/classes#feedback)
* Content Source: [spec/classes.md](https://github.com/dotnet/csharplang.zh-tw/blob/live/spec/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @s0920832252
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
