### ISSUE TITLE
標點符號混淆

### ISSUE THREAD

**Issue by ragnakuei** [dotnet/docs.zh-tw#265]
有點地方的點，標成了 2。1，正確的應該是 2.1 !

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [SDK 樣式專案中的目標 framework-.NET](https://docs.microsoft.com/zh-tw/dotnet/standard/frameworks?source=docs#feedback)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by srvbpigh** [comment]
Hello, @ragnakuei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
