### ISSUE TITLE
語法與翻譯有誤

### ISSUE THREAD

**Issue by tracyxxlee** [dotnet/docs.zh-tw#266]
"不過，請不要犯任何錯誤，其餘部分仍會持續一段時間。 它仍然是針對公開公開的 Api 擅長，基於回溯相容性的理由。"

=> 語法與翻譯有誤：
建議改為如下：

"不過，請不要誤會，因為在開放 API 與向後相容的傑出特性，REST 仍會存在很長一段時間。"

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: dc86015f-c6c7-5fdc-ae0f-c69353afcb34
* Version Independent ID: 491d7006-ae8d-fb74-8b29-7e4b5031fcae
* Content: [REST 和 gRPC](https://docs.microsoft.com/zh-tw/dotnet/architecture/cloud-native/rest-grpc#feedback)
* Content Source: [docs/architecture/cloud-native/rest-grpc.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/architecture/cloud-native/rest-grpc.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @robvet
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @tracyxxlee
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
您好，@tracyxxlee，   

謝謝您的寶貴意見。  

我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/dotnet/architecture/cloud-native/rest-grpc#feedback。   

我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。  

順頌時祺  
Microsoft DOCS 國際小組
