### ISSUE TITLE
{2>版本<2}

### ISSUE THREAD

**Issue by doggy8088** [dotnet/docs.zh-tw#268]
There is a `{2&gt;版本&lt;2}` in the doc.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: a1200f60-5ad1-2b1e-067d-07f2dd442915
* Version Independent ID: 0e53d9c7-32ca-1341-f89a-a901a5636a9d
* Content: [.NET Core SDK 和執行時間相依性-.NET Core](https://docs.microsoft.com/zh-tw/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows)
* Content Source: [docs/core/install/dependencies.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/core/install/dependencies.md)
* Product: **dotnet-core**
* GitHub Login: @leecow
* Microsoft Alias: **leecow**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
