### ISSUE TITLE
The title should change to 教學課程：建立項目範本

### ISSUE THREAD

**Issue by doggy8088** [dotnet/docs.zh-tw#271]
The "Item Template" in Traditional Chinese should be `項目範本`.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [針對 dotnet new 建立項目範本 - .NET Core CLI - .NET Core](https://docs.microsoft.com/zh-tw/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@doggy8088 您好： 

感謝您的參與。 

目前不接受參與機器翻譯內容的翻譯問題。 

我們很重視您對人工翻譯內容的意見反應與建議，並使用這些意見來訓練機器翻譯引擎，因此，您的貢獻內容會隨著時間改善人工與機器翻譯的品質。 

您可以根據各個內容檔案標頭的 ms.translationtype 中繼資料值 “HT”，分辨出人工翻譯的主題，其他則是機器翻譯的主題 (值為 “MT” 代表機器翻譯)。 

非常感謝您的支援。 

Microsoft DOCS 全球體驗小組
