### ISSUE TITLE
bash 不應該翻譯為【反斜線】

### ISSUE THREAD

**Issue by doggy8088** [dotnet/docs.zh-tw#273]
https://docs.microsoft.com/zh-tw/dotnet/core/tools/enable-tab-autocomplete#bash

`bash` 不應該翻譯為【反斜線】，建議保留 `bash` 就好

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 341f0255-aa31-8e76-9b17-1232b7a910a9
* Version Independent ID: f30f63dc-0d90-7dba-ef39-b0148c637c1a
* Content: [啟用 tab 鍵自動完成 - .NET Core CLI](https://docs.microsoft.com/zh-tw/dotnet/core/tools/enable-tab-autocomplete#bash)
* Content Source: [docs/core/tools/enable-tab-autocomplete.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/core/tools/enable-tab-autocomplete.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@doggy8088 您好： 
 
感謝您的參與。 
  
目前不接受參與機器翻譯內容的翻譯問題。 
 
我們很重視您對人工翻譯內容的意見反應與建議，並使用這些意見來訓練機器翻譯引擎，因此，您的貢獻內容會隨著時間改善人工與機器翻譯的品質。 
 
您可以根據各個內容檔案標頭的 ms.translationtype 中繼資料值 “HT”，分辨出人工翻譯的主題，其他則是機器翻譯的主題 (值為 “MT” 代表機器翻譯)。 

非常感謝您的支援。 

Microsoft DOCS 全球體驗小組
