### ISSUE TITLE
.NET Core 不該翻成 酷睿

### ISSUE THREAD

**Issue by kaibaooo** [dotnet/docs.zh-tw#275]
https://docs.microsoft.com/zh-tw/dotnet/core/#download-net-core

> 下載.NET 核心 SDK，在 Windows、macOS 或 Linux 電腦上嘗試 .NET 酷睿。 如果您更喜歡使用 Docker 容器，請訪問.NET 核心 Docker 集線器 。

大部分都保留為 .NET Core 但這裡有一處卻翻成`酷睿`，應該要修正回`Core`

**Comment by srvbpigh** [comment]
Hello, @kaibaooo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@kaibaooo

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
