### ISSUE TITLE
Page Visual C# 程式設計人員的其他資源 (additional-resources.md) - suggestion

### ISSUE THREAD

**Issue by alantsai** [dotnet/docs.zh-tw#68]
file reference 
https://github.com/dotnet/docs.zh-tw/blob/live/docs/csharp/getting-started/additional-resources.md

some suggestion (not sure if this is correct place to put this, or should go to the English doc repo, but I will leave it here) :

1. since codeplex is closing, is it not better to suggest other place like github as host open source project
2. link for MSDN C# 社群網站 (http://go.microsoft.com/fwlink/?LinkId=165945) is a broken link

**Comment by nokura** [comment]
Thank you for your comment. For #2, it should go to https://msdn.microsoft.com/zh-tw/vstudio/dd314520. Do you see it in your browser?

**Comment by mairaw** [comment]
And for issue 1, we're updating our English content to replace codeplex links. See tracking issue here: https://github.com/dotnet/docs/issues/2974

That page in particular was removed since this issue was opened.

**Comment by alantsai** [comment]
@nokura 
it seems like that page have been removed in the latest version, I guess it is not a issue anymore

@mairaw 
thanks for the info

I will close this issue
